spring.application.name=${REVIEW_SERVICE_NAME:review-service}

server.port=${PORT:8083}

spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always